name: Rust

on:
  push:
    branches: [ master ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --verbose --all
    - name: Run tests
      run: cargo test --verbose --all

  fuzz_simple_automata:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install cargo fuzz
      run: cargo install cargo-fuzz
    - name: Build fuzz target
      run: cargo fuzz build simple_automata -Oa --sanitizer=none
    - name: Run simple_automata fuzz target
      run: cargo fuzz run simple_automata -Oa --sanitizer=none -- -runs=50000

  fuzz_fst_differential:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install cargo fuzz
      run: cargo install cargo-fuzz
    - name: Build fuzz target
      run: cargo fuzz build fst_differential -Oa --sanitizer=none
    - name: Run fst_differential fuzz target
      run: cargo fuzz run fst_differential -Oa --sanitizer=none -- -runs=5000
